
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SGecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SampleSecurityGroup
      GroupDescription: SG For Web Server
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443
